CREATE VIEW TICKETS_CONTROL AS
SELECT TIC.SLA,TIP.NOMBRE AS TIPOLOGIA,ETI.DESCRIPCION AS ESTADO,COUNT(*) AS CANTIDAD,MAX(TIC.FECHA_RESOLUCION) AS [ULTIMA RESOLUCIÓN]
FROM TICKET AS TIC
INNER JOIN TIPOLOGIA AS TIP ON TIP.ID_TIPOLOGIA = TIC.TipologiaId_tipologia
INNER JOIN ESTADOTICKET AS ETI ON ETI.ID_ESTADO_TICKET = TIC.EstadoTicketId_estado_ticket
GROUP BY TIC.SLA,	TIP.NOMBRE,	ETI.DESCRIPCION 