USE telenot
/*INSERTS DE ESTADOS PARA CLIENTES*/
INSERT INTO ESTADOCLI (NOMBRE)
VALUES ('ACTIVO')

INSERT INTO ESTADOCLI (NOMBRE)
VALUES ('INACTIVO')

INSERT INTO ESTADOCLI (NOMBRE)
VALUES ('PROSPECTO')


/*INSERTS DE ESTADOS PARA TICKETS*/

INSERT INTO ESTADOTICKET (DESCRIPCION)
VALUES ('ABIERTO')

INSERT INTO ESTADOTICKET (DESCRIPCION)
VALUES ('EN PROGRESO')

INSERT INTO ESTADOTICKET (DESCRIPCION)
VALUES ('PENDIENTE CLIENTE')

INSERT INTO ESTADOTICKET (DESCRIPCION)
VALUES ('RESUELTO')

INSERT INTO ESTADOTICKET (DESCRIPCION)
VALUES ('CERRADO')

/*INSERTS DE TIPO DE SERVICIO*/

INSERT INTO TIPOSERVICIO(NOMBRE)
VALUES ('TELEFONIA FIJA')

INSERT INTO TIPOSERVICIO(NOMBRE)
VALUES ('INTERNET')

INSERT INTO TIPOSERVICIO(NOMBRE)
VALUES ('VOIP')

/*INSERTS DE TIPO DE TIPOLOGIAS*/

INSERT INTO TIPOLOGIA (NOMBRE, SLA)
VALUES ('CRITICA','1')

INSERT INTO TIPOLOGIA (NOMBRE, SLA)
VALUES ('ALTA','2')

INSERT INTO TIPOLOGIA (NOMBRE, SLA)
VALUES ('MEDIA','5')

INSERT INTO TIPOLOGIA (NOMBRE, SLA)
VALUES ('BAJA','7')
